name: Generate Candidate PDF

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Config for generating the PDF'
        required: true
      survey-header:
        description: 'Survey Response Header from CSV'
        required: true
      candidate-response:
        description: 'Survey Response Row from CSV'
        required: true

jobs:
  generate-candidate-pdf:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get python version
      run: |
        python_version=$(cat .python-version)
        echo "python_version=${python_version}" >> $GITHUB_ENV

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}

    - name: Install CLI
      run: |
        pipx install .

    - name: Write Inputs to File
      run: |
        mkdir campaign
        echo '${{ github.event.inputs.survey-header }}' >> campaign/responses.csv
        echo '${{ github.event.inputs.candidate-response }}' >> campaign/responses.csv
        echo '${{ github.event.inputs.config }}' > campaign/config.json
        mkdir campaign/logos

    - name: Run CLI
      run: |
        candidate-surveys generate-pdfs --responses campaign/responses.csv --config campaign/config.json --logos campaign/logos --output campaign/output

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-pdf
        path: campaign/output
